version: '3.7'


services:
  app:
    build: ./
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_HOST
      - APP_PORT
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGHOST
      - PGPORT
    depends_on:
      sql_db:
        condition: service_healthy

  sql_db:
    image: postgres:13
    restart: always
    ports:
      - "${PGPORT}:${PGPORT}"
    environment:
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGHOST
      - PGPORT
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "main_db"]
      interval: 5s
      timeout: 5s
      retries: 15


volumes:
  db-data:
