version: '3.7'


services:
  app:
    build: ./
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_HOST
      - APP_PORT
      # - PGUSER
      # - PGPASSWORD
      # - PGDATABASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGHOST
      - PGPORT
    depends_on:
      sql_db:
        condition: service_healthy

  sql_db:
    image: postgres:13
    restart: always
    ports:
      - "${PGPORT}:${PGPORT}"
    environment:
      # - PGUSER
      # - PGPASSWORD
      # - PGDATABASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGHOST
      - PGPORT
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 15


volumes:
  db-data:
