version: '3.7'


services:
  app:
    build: ./
    ports:
      - "5050:5050"
    env_file:
      - app.env
    depends_on:
      # - "sql_db"
      sql_db:
        condition: service_healthy

  sql_db:
    image: postgres:13
    restart: always
    ports:
      - "5070:5070"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - sql_db.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "main_db"]
      interval: 5s
      timeout: 5s
      retries: 15


volumes:
  db-data:
